#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Ipkg
version:      0.03
version_from: Ipkg.pm
installdirs:  site
requires:
    Archive::Tar:                  0.072
    Compress::Zlib:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
